### ISSUE TITLE
Should we do submit from cmd line only?

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/cacts#10]
Currently, we still [rely](https://github.com/E3SM-Project/cacts/blob/a0d7fce341893760cf322c0cfc208b6aa3a87b41/cacts/cacts.py#L378) on the presence of a CTestConfig.cmake script in the project root dir. This seems to be a bit arbitrary, and maybe we should move this to more options in the `project` section of the yaml file.

Currently, the project section looks like this:

```yaml
project:
  name: EAMxx
  baseline_gen_label: baseline_gen
  baseline_summary_file: baseline_list
  enable_baselines_cmake_option: SCREAM_ENABLE_BASELINE_TESTS
```

Perhaps we could extend with
```yaml
project:
  name: EAMxx
  baseline_gen_label: baseline_gen
  baseline_summary_file: baseline_list
  enable_baselines_cmake_option: SCREAM_ENABLE_BASELINE_TESTS
  cdash:
    project_name: SCREAM
    drop_method: https
    url: https://my.cdash.org/submit.php?project=E3SM
    track: E3SM_SCREAM
```
drop site can be hard-coded to the machine name by CACTS (adding `drop_site: ${machihe.name}` to project would make var expansion complicated, since assume project is fully formed when we expand vars in machine).
