### ISSUE TITLE
Allow inheritance for machine/builds sections in the yaml file

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/cacts#7]
Something like

```yaml
machines:
   cray:
      cxx_compiler: CC
      c_compiler: cc
      ftn_compiler: ftn
   pm-cpu:
      extends: cray
      baselines_dir: /path/to/pm-cpu-baselines
   pm-gpu:
      extends: cray
      baselines_dir: /path/to/pm-gpu-baselines
```
If `extends` (or `inherit` or similar) is found, make the parser parse that section first, then update with the current machine's settings. This can avoid duplication and keep yaml config files for large projects smaller.
